import random

class GoldenBank:
  value_lyst = []
  original_values = []
    
  def __init__(self, value_file):
    '''initializes GoldenBank object'''
    file = open(value_file)

    #one check to ensure unedited value file
    assert(file.readline() == "-----------DO NOT EDIT THIS FILE-----------\n"), "ERROR: VALUE FILE EDITED"

    #value parsing using CSL
    values = file.read()
    self.original_values = values.split(", ")

    #check to ensure file has 100 values
    assert len(self.original_values) == 100, "ERROR: VALUE FILE EDITED"

    #check to make sure value file only contains 100 integer values
    try:
      for value in self.original_values:
        int(value)
    except:
      assert(False), "ERROR: VALUE FILE EDITED"

    file.close()

  def randomize(self):
      '''randomizes the golden bank'''
      random.shuffle(self.value_lyst)

  def generateBall(self):
      '''generates a ball from the golden bank'''
      return self.value_lyst.pop()

  def reset(self):
    '''clears the distribution panel of all balls'''
    self.value_lyst = self.original_values
